import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const SITE_URL = "https://usegeoaeo.com";
const REPO_URL = "https://github.com/pooriaarab/usegeoaeo";

async function generate(source: string, target: string, exportName: string) {
  const markdown = await readFile(source, "utf8");
  const output = [
    "// Generated by scripts/generate-design-context.ts. Do not edit.",
    `export const ${exportName} = ${JSON.stringify(markdown)};`,
    "",
  ].join("\n");

  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output);
}

// Machine-readable design guide, served at /design.md.
await generate(
  resolve(scriptDirectory, "../../../.agents/design.md"),
  resolve(scriptDirectory, "../src/generated/design-context.generated.ts"),
  "designContext",
);

// Operating guide for agents, served at /agents.md. Read from disk at build
// time and bundled as a constant: the worker runtime has no repo filesystem,
// so a request-time readFileSync 500s in production.
await generate(
  resolve(scriptDirectory, "../../../AGENTS.md"),
  resolve(scriptDirectory, "../src/generated/agents-md.generated.ts"),
  "agentsMd",
);

// MCP server card, served at /.well-known/mcp/server-card.json. Emitted from
// the canonical registry document so the route cannot drift from it.
await generate(
  resolve(scriptDirectory, "../../../server.json"),
  resolve(scriptDirectory, "../src/generated/server-card.generated.ts"),
  "serverCardJson",
);

// Agent skills index, served at /.well-known/agent-skills/index.json, plus the
// raw SKILL.md bodies served under the same prefix. Derived from the skills
// that actually ship in .claude/skills, so the index cannot drift from them.
const skillsDirectory = resolve(scriptDirectory, "../../../.claude/skills");
const skills: Array<{
  id: string;
  name: string;
  description: string;
  url: string;
  source: string;
}> = [];
const skillMarkdown: Record<string, string> = {};
const skillDirs = await readdir(skillsDirectory).catch(() => [] as string[]);
const loadedSkills = await Promise.all(
  skillDirs.map(async (entry) => ({
    entry,
    markdown: await readFile(resolve(skillsDirectory, entry, "SKILL.md"), "utf8").catch(() => ""),
  })),
);
for (const { entry, markdown } of loadedSkills) {
  if (!markdown) continue;
  const frontmatter = markdown.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? "";
  skills.push({
    id: entry,
    name: frontmatter.match(/^name:\s*(.+)$/m)?.[1]?.trim() ?? entry,
    description: frontmatter.match(/^description:\s*(.+)$/m)?.[1]?.trim() ?? "",
    url: `${SITE_URL}/.well-known/agent-skills/${entry}/SKILL.md`,
    source: `${REPO_URL}/blob/main/.claude/skills/${entry}/SKILL.md`,
  });
  skillMarkdown[entry] = markdown;
}
skills.sort((a, b) => a.id.localeCompare(b.id));
await writeFile(
  resolve(scriptDirectory, "../src/generated/agent-skills.generated.ts"),
  [
    "// Generated by scripts/generate-design-context.ts. Do not edit.",
    `export const agentSkillsIndex = ${JSON.stringify({ skills }, null, 2)} as const;`,
    `export const skillMarkdown: Record<string, string> = ${JSON.stringify(skillMarkdown)};`,
    "",
  ].join("\n"),
);
