import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const source = resolve(scriptDirectory, "../../../.agents/design.md");
const target = resolve(
  scriptDirectory,
  "../src/generated/design-context.generated.ts",
);
const markdown = await readFile(source, "utf8");
const output = [
  "// Generated by scripts/generate-design-context.ts. Do not edit.",
  `export const designContext = ${JSON.stringify(markdown)};`,
  "",
].join("\n");

await mkdir(dirname(target), { recursive: true });
await writeFile(target, output);
