import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));

async function generate(source: string, target: string, exportName: string) {
  const markdown = await readFile(source, "utf8");
  const output = [
    "// Generated by scripts/generate-design-context.ts. Do not edit.",
    `export const ${exportName} = ${JSON.stringify(markdown)};`,
    "",
  ].join("\n");

  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output);
}

// Machine-readable design guide, served at /design.md.
await generate(
  resolve(scriptDirectory, "../../../.agents/design.md"),
  resolve(scriptDirectory, "../src/generated/design-context.generated.ts"),
  "designContext",
);

// Operating guide for agents, served at /agents.md. Read from disk at build
// time and bundled as a constant: the worker runtime has no repo filesystem,
// so a request-time readFileSync 500s in production.
await generate(
  resolve(scriptDirectory, "../../../AGENTS.md"),
  resolve(scriptDirectory, "../src/generated/agents-md.generated.ts"),
  "agentsMd",
);
